repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 5.13.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 24.8.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: eb1df347edd128b30cd3368dddc3aa65edcfac38
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
  - id: mdformat
    files: 'README.md'
